### ISSUE TITLE
A permissions to "Administer CiviCRM" is required for anyone creating new Events when this extension is turned on

### ISSUE THREAD

**Issue by kasiawaka** [veda-consulting/uk.co.vedaconsulting.gotowebinar#21]
Situation: an organization has several users who are allowed to create new Events but they are not allowed to administer CiviCRM settings. If the user has a permission to create/edit Events and this extension is turned on - but that user doesn't have a permission to "Administer CiviCRM", the following error appears on the Event create/edit page:
"API permission check failed for CustomField/get call; insufficient permission: require administer CiviCRM and access all custom data"

If the user continue to work with the event and changes any information about it (like the event description), that information is being modified on the screen but when the event is saved, the changes are not saved (and not additional errors are shown).

This is not really a bug - more of a use case scenario where there are different users (than administrators) that are allowed to create events.  

I'm wondering if the possible improvements would be:
1. users who don't have "Administer CiviCRM" permissions would not be able to see any of the Webinar functionality on the events create/edit page (so not see the custom field Webinar Key and the drop down list of webinars from Citrix)

2. only users with "Administer CiviCRM" can modify the extension GoToWebinar settings (on this page: civicrm/gotowebinar/settings?reset=1) but all users with "CiviEvent: edit all events" permissions could continue editing the events, including selecting the Citrix GoToWebinar to link to.

3. (the fancy way) A new permissions for "Sync Events with Citrix GoToWebinar" to allow only those users to edit/assign Webinar Key to events. This solution would still require option 2 working - ie. users without this new permission but also without "Administer CiviCRM" should be able to edit events.

Please let me know if I can help with this improvement in any way.

**Comment by veda-consulting** [comment]
Hi Kasia - Good suggestions, we can make these tweaks when we next have a ‘free’ window. If they’re a priority for you then let us know, we can maybe come to some sort of arrangement.

**Comment by Kajakaran** [comment]
@kasiawaka 

We have released v 1.6.1 and added permission from administer civicrm to access civievent.
Thanks

**Comment by kasiawaka** [comment]
Thanks @Kajakaran 
I'm testing the 1.6.1, version. I have a test group for managers with a permission to "access CiviEvent" (but not "Administer CiviCRM") and on the event edit, they unfortunately still get the same error as before: "API permission check failed for CustomField/get call; insufficient permission: require administer CiviCRM and access all custom data".  
I cleared cache and rebuilt menus but there is no change. I also disabled and re-enabled the extension.
Yes, that group has permission to "CiviCRM: access all custom data"

The problem only manifests when editing the event, not when creating it (the URL is civicrm/event/manage/settings&reset=1&action=update&id=XXX)

**Comment by Kajakaran** [comment]
@kasiawaka 

Which version of CiviCRM and environment are you testing?
What permissions do your test group have in addition to 'access CiviEvent'?

Thanks

**Comment by Kajakaran** [comment]
@kasiawaka 

We have released 1.6.2 version. Can you test now?

**Comment by kasiawaka** [comment]
@Kajakaran Great news, this is working now, no errors. A user with no permissions to Administer CiviCRM is now able to create/edit CiviCRM events with this extension enabled.
